<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>Antigen.Common</PackageId>
        <Description>Shared analyzer components for Bethesda mod analysis.</Description>
        <RootNamespace>Antigen</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Antigen.SDK\Antigen.SDK.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="GitVersion.MsBuild">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
    </ItemGroup>

</Project>
